port = 4242
release_bind = [
    "KeyLeftCtrl",
    "KeyLeftShift",
    "KeyLeftMeta",
    "KeyLeftAlt",
]

[[clients]]
hostname = "fornax"
ips = ["192.168.145.36"]
position = "left"
activate_on_startup = true

[[clients]]
hostname = "nox"
ips = []
position = "left"

[authorized_fingerprints]
"bd:7d:e6:3b:d9:a0:58:1c:d8:99:c8:f5:80:84:ca:5e:18:2b:7f:d9:3f:93:85:8a:e9:dd:40:08:4d:fd:fc:2f" = "fornaxs"
