#!/usr/bin/env bash
# JankyBorders config
# Owner: Homebrew service. AeroSpace intentionally does not start borders.

borders \
  style=round \
  width=12.0 \
  hidpi=on \
  active_color=0xff00ff66 \
  inactive_color=0xff1e1e2e
