# Optional fornax input feature: make ALT behave as SUPER/Windows.
# To enable, uncomment the input block below and run `dotfiles update`.

 input {
     kb_options = compose:caps,altwin:swap_alt_win
 }
