#!/usr/bin/env bash
set -euo pipefail
# Generate profile metadata for scripts and desktop helpers.
#
# The profile remains the source of truth. This script writes a small shell env
# file under ~/.config/dotfiles so stowed helper scripts can consume profile
# intent without re-sourcing repo internals.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
# shellcheck source=scripts/lib.sh
. "$SCRIPT_DIR/lib.sh"

PROFILES_DIR="${PROFILES_DIR:-$REPO_DIR/profiles}"
PROFILE="" OS=""

while [ $# -gt 0 ]; do
  case "$1" in
    --profile) PROFILE="${2:-}"; shift 2 ;;
    --profile=*) PROFILE="${1#*=}"; shift ;;
    --os) OS="${2:-}"; shift 2 ;;
    --os=*) OS="${1#*=}"; shift ;;
    *) die "configure-profile-settings: unknown arg: $1" ;;
  esac
done

[ -n "$PROFILE" ] || die "configure-profile-settings: --profile required"
[ -f "$PROFILES_DIR/$PROFILE.conf" ] || die "configure-profile-settings: unknown profile: $PROFILE"

DISPLAY_CLASS=""
DISPLAY_DEFAULT_RESOLUTION=""
DISPLAY_DEFAULT_SCALE=""
DISPLAY_LAYOUT_HINT=""
QUICK_SURFACE_MONITOR_MODE=""
QUICK_SURFACE_NOTES_WIDTH_PERCENT=""
QUICK_SURFACE_QUAKE_HEIGHT_PERCENT=""
QUICK_SURFACE_TOP_OFFSET=""
QUICK_SURFACE_BOTTOM_OFFSET=""
DISPLAY_MODES=()
HARDWARE_PACKAGE_GROUPS=()

# shellcheck source=/dev/null
. "$PROFILES_DIR/$PROFILE.conf"

quote_value() {
  printf '%q' "$1"
}

write_export() {
  local name="$1" value="$2"
  printf 'export %s=%s\n' "$name" "$(quote_value "$value")"
}

write_array_comment() {
  local title="$1"; shift
  local item
  [ "$#" -gt 0 ] || return 0
  printf '# %s:\n' "$title"
  for item in "$@"; do
    printf '# - %s\n' "$item"
  done
}

main() {
  local config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles"
  local env_file="$config_dir/profile.env"
  local ghostty_profile="$config_dir/ghostty-profile"

  if [ "$DRY_RUN" = "1" ]; then
    info "[dry-run] would write profile settings to $env_file"
    return 0
  fi

  run mkdir -p "$config_dir"
  {
    printf '# Generated by dotfiles. Do not edit directly.\n'
    printf '# Source profile: %s\n\n' "$PROFILE"
    write_export DOTFILES_PROFILE "$PROFILE"
    write_export DOTFILES_OS "$OS"
    write_export DOTFILES_DISPLAY_CLASS "${DISPLAY_CLASS:-}"
    write_export DOTFILES_DISPLAY_DEFAULT_RESOLUTION "${DISPLAY_DEFAULT_RESOLUTION:-}"
    write_export DOTFILES_DISPLAY_DEFAULT_SCALE "${DISPLAY_DEFAULT_SCALE:-}"
    write_export DOTFILES_DISPLAY_LAYOUT_HINT "${DISPLAY_LAYOUT_HINT:-}"
    write_export DOTFILES_QUICK_SURFACE_MONITOR_MODE "${QUICK_SURFACE_MONITOR_MODE:-focused}"
    write_export DOTFILES_QUICK_SURFACE_NOTES_WIDTH_PERCENT "${QUICK_SURFACE_NOTES_WIDTH_PERCENT:-28}"
    write_export DOTFILES_QUICK_SURFACE_QUAKE_HEIGHT_PERCENT "${QUICK_SURFACE_QUAKE_HEIGHT_PERCENT:-48}"
    write_export DOTFILES_QUICK_SURFACE_TOP_OFFSET "${QUICK_SURFACE_TOP_OFFSET:-28}"
    write_export DOTFILES_QUICK_SURFACE_BOTTOM_OFFSET "${QUICK_SURFACE_BOTTOM_OFFSET:-28}"
    printf '\n'
    [ "${#DISPLAY_MODES[@]}" -gt 0 ] && write_array_comment DISPLAY_MODES "${DISPLAY_MODES[@]}"
    [ "${#HARDWARE_PACKAGE_GROUPS[@]}" -gt 0 ] && write_array_comment HARDWARE_PACKAGE_GROUPS "${HARDWARE_PACKAGE_GROUPS[@]}"
  } >"$env_file"

  rm -f "$ghostty_profile"
  if [ "$PROFILE" = "laptop-work-omarchy" ]; then
    printf '# Generated by dotfiles. Do not edit directly.\nfont-size = 12\n' >"$ghostty_profile"
  fi

  ok "Profile settings written: $env_file"
}

main
